version: '3.4'

services:
  myapp-container:
    build:
      context: .
      dockerfile: Dockerfile.txt
    environment:
      - connectionStrings_DefaultConnection=Username=myuser;Password=mypassword;Server=postgresql;Port=5432;Database=mydatabase;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "9090:80"
    depends_on:
      - "postgresql"
    networks:
      - my-network
    container_name: myapp-container

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./Tables/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./Tables/initelements.sql:/docker-entrypoint-initdb.d/initelements.sql
    networks:
      - my-network
    restart: always

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
